import { test, expect } from '@playwright/test';

// Auto-generated by TollGate Pipeline
// 2026-04-09T09:34:25.936Z

test.describe('Authentication Page', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:3000');

    // Navigate to http://localhost:3000/auth
    await page.goto('http://localhost:3000/auth');

    // Take a snapshot of the page
    await expect(page).toHaveScreenshot();

    // Assert the page contains a login form
    await expect(page.getByText('a login form')).toBeVisible();

  });
});
