import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-03-14T00:35:02.142Z

test.describe('Dashboard Access', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to http://localhost:5173/dashboard
    await page.goto('http://localhost:5173/dashboard');

    // Take a snapshot of the page
    await expect(page).toHaveScreenshot();

  });
});
