import { test, expect } from '@playwright/test';

// Auto-generated by TollGate Pipeline
// 2026-04-08T23:54:00.116Z

test.describe('Landing Page Verification', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:3000');

    // Navigate to http://localhost:3000
    await page.goto('http://localhost:3000');

    // Take a snapshot of the page
    await expect(page).toHaveScreenshot();

    // Assert the page contains the main heading
    await expect(page.getByText('the main heading')).toBeVisible();

  });
});
