import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-03-13T21:32:47.340Z

test.describe('Scenario: Dashboard loads successfully', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to /dashboard
    await page.goto('http://localhost:5173/dashboard');

    // Assert page contains "Welcome to your dashboard"
    await expect(page.getByText('Welcome to your dashboard')).toBeVisible();

    // Assert page contains "Recent Activity"
    await expect(page.getByText('Recent Activity')).toBeVisible();

    // Assert page contains "User Statistics"
    await expect(page.getByText('User Statistics')).toBeVisible();

  });
});
