import { test, expect } from '@playwright/test';

// Auto-generated by TollGate Pipeline
// 2026-04-09T03:38:00.106Z

test.describe('Scenario: Verify Active Sessions Value', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:3000');

    // Navigate to "/dashboard"
    await page.goto('http://localhost:3000/"/dashboard"');

    // Assert page contains "1,240"
    await expect(page.getByText('1,240')).toBeVisible();

  });
});
