import { test, expect } from '@playwright/test';

// Auto-generated by TollGate Pipeline
// 2026-04-08T23:42:03.002Z

test.describe('Scenario: Verify Active Sessions Value', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:3000');

    // Navigate to "/dashboard"
    await page.goto('http://localhost:3000/"/dashboard"');

    // Assert page contains "Active Sessions"
    await expect(page.getByText('Active Sessions')).toBeVisible();

    // Assert page contains value "-42"
    await expect(page.getByText('value "-42')).toBeVisible();

  });
});
