import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-04-08T18:26:19.665Z

test.describe('Scenario: Verify Recent Activity Title on Dashboard', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:3000');

    // Navigate to "/dashboard"
    await page.goto('http://localhost:3000/"/dashboard"');

    // Assert page contains "Recent Activity"
    await expect(page.getByText('Recent Activity')).toBeVisible();

  });
});
