import { test, expect } from '@playwright/test';

// Auto-generated by TollGate Pipeline
// 2026-04-08T19:12:50.156Z

test.describe('Scenario: Verify Header Component Renders Correctly', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:3000');

    // Navigate to "/"
    await page.goto('http://localhost:3000/"/"');

    // Assert page contains "Good morning, Alex"
    await expect(page.getByText('Good morning, Alex')).toBeVisible();

  });
});
