import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-03-14T04:31:35.139Z

test.describe('Scenario: Verify correct dashboard title', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to "/"
    await page.goto('http://localhost:5173/');

    // Assert page contains "Welcome to the Admin Panel"
    await expect(page.getByText('Welcome to the Admin Panel')).toBeVisible();

  });
});
