import { test, expect } from '@playwright/test';

// Auto-generated by TollGate Pipeline
// 2026-04-09T06:37:10.173Z

test.describe('Scenario: Verify User Greeting in Header', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:3000');

    // Navigate to "/dashboard"
    await page.goto('http://localhost:3000/"/dashboard"');

    // Assert page contains "Good morning, Alex"
    await expect(page.getByText('Good morning, Alex')).toBeVisible();

  });
});
