import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-03-13T21:17:16.205Z

test.describe('Scenario: User can log out', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to /dashboard
    await page.goto('http://localhost:5173/dashboard');

    // Click "Logout"
    await page.getByRole('button', { name: 'Logout' }).or(page.getByRole('link', { name: 'Logout' })).click();

    // Assert page contains "You have been logged out"
    await expect(page.getByText('You have been logged out')).toBeVisible();

    // Assert page contains "Sign in"
    await expect(page.getByText('Sign in')).toBeVisible();

  });
});
