import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-03-13T22:16:09.535Z

test.describe('Scenario: Verify the correct testid for Recent Activity title on Dashboard', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to "/"
    await page.goto('http://localhost:5173/"/"');

    // Assert page contains element with data-testid "recent-activity-title"
    await expect(page.getByText('element with data-testid "recent-activity-title')).toBeVisible();

  });
});
