import { test, expect } from '@playwright/test';

// Auto-generated by TollGate Pipeline
// 2026-04-09T05:04:06.951Z

test.describe('Scenario: Verify Dashboard Announcement Test ID', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:3000');

    // Navigate to "/dashboard"
    await page.goto('http://localhost:3000/"/dashboard"');

    // Assert page contains element with data-testid "dashboard-announcement"
    await expect(page.getByText('element with data-testid "dashboard-announcement')).toBeVisible();

  });
});
