import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-03-13T22:08:17.933Z

test.describe('Scenario: Dashboard page loads', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to /dashboard
    await page.goto('http://localhost:5173/dashboard');

    // Assert page contains "Welcome"
    await expect(page.getByText('Welcome')).toBeVisible();

    // Assert page contains "Recent Activities"
    await expect(page.getByText('Recent Activities')).toBeVisible();

  });
});
