import { test, expect } from '@playwright/test';

// Auto-generated by TollGate Pipeline
// 2026-04-09T03:59:13.693Z

test.describe('Scenario: Verify Dashboard Route Accessibility', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:3000');

    // Navigate to "/dashboard"
    await page.goto('http://localhost:3000/"/dashboard"');

    // Assert page contains "Dashboard Overview"
    await expect(page.getByText('Dashboard Overview')).toBeVisible();

  });
});
