import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-03-13T21:11:07.366Z

test.describe('Scenario: User profile is accessible', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to /dashboard
    await page.goto('http://localhost:5173/dashboard');

    // Click "Profile"
    await page.getByRole('button', { name: 'Profile' }).or(page.getByRole('link', { name: 'Profile' })).click();

    // Assert page contains "User Profile"
    await expect(page.getByText('User Profile')).toBeVisible();

    // Assert page contains "Edit Profile"
    await expect(page.getByText('Edit Profile')).toBeVisible();

  });
});
