import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-03-13T23:55:56.484Z

test.describe('Scenario: Verify the Recent Activity section title on Dashboard', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to "/"
    await page.goto('http://localhost:5173/"/"');

    // Assert page contains "Recent Activity"
    await expect(page.getByText('Recent Activity')).toBeVisible();

  });
});
