import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-03-13T21:50:05.800Z

test.describe('Scenario: Recent Activity title is rendered correctly', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to /dashboard
    await page.goto('http://localhost:5173/dashboard');

    // Assert page contains "Recent Activity"
    await expect(page.getByText('Recent Activity')).toBeVisible();

  });
});
