import { test, expect } from '@playwright/test';

// Auto-generated by TollGate Pipeline
// 2026-04-08T23:20:17.945Z

test.describe('Scenario: Verify Clickability of Edit Profile Button', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:3000');

    // Navigate to "/profile"
    await page.goto('http://localhost:3000/"/profile"');

    // Click "Edit Profile"
    await page.getByRole('button', { name: 'Edit Profile' }).or(page.getByRole('link', { name: 'Edit Profile' })).click();

  });
});
