import { test, expect } from '@playwright/test';

// Auto-generated by TollGate Pipeline
// 2026-04-09T05:19:06.155Z

test.describe('Scenario: Verify Recent Activity Title TestID', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:3000');

    // Navigate to "/dashboard"
    await page.goto('http://localhost:3000/"/dashboard"');

    // Assert page contains element with data-testid "recent-activity-title"
    await expect(page.getByText('element with data-testid "recent-activity-title')).toBeVisible();

  });
});
