import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-03-14T04:04:58.315Z

test.describe('Scenario: Verify the "Recent Activity" heading is displayed correctly on the Dashboard', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to "/"
    await page.goto('http://localhost:5173/"/"');

    // Assert page contains "Recent Activity"
    await expect(page.getByText('Recent Activity')).toBeVisible();

  });
});
