import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-03-14T00:10:02.692Z

test.describe('Scenario: Verify the Recent Activity section is rendered correctly', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:5173');

    // Navigate to "/"
    await page.goto('http://localhost:5173/"/"');

    // Assert page contains "Recent Activity"
    await expect(page.getByText('Recent Activity')).toBeVisible();

    // Assert page contains element with data-testid "recent-activity-title"
    await expect(page.getByText('element with data-testid "recent-activity-title')).toBeVisible();

  });
});
